### PR TITLE
Add Monero-CSharp

### PR DESCRIPTION
**Pull request by Agorist-Action**
Adding Monero CSharp.

### CODE REVIEW

**Comment by Agorist-Action** [comment]
Once all this gets added to the website. @erciccione can you make the announcement I previously mentioned on Reddit, and other social media outlets? I left you a template announcement to be customized should you see fit. You have a lot more credibility in the community than I do. I'm just a stranger on the internet that wants to see Monero succeed.

**Review by erciccione — APPROVED** [review]
Looks good to me.

**Comment by erciccione** [comment]
> can you make the announcement I previously mentioned on Reddit, and other social media outlets?

Sure, no problem.

**Comment by Agorist-Action** [comment]
Thanks for reviewing.

Also, I didn't request any funding for my work; so, if you can include my donation address (`89CkXKw3MQLXAinJz2eb8ohmGdDasGxun65ArenNuqXFfDSVbhiqpte4E2PQaxT4yPbsNSXkT4hR2QMFYQneZfBoCX19Wx2`) in the post, that would be helpful.

Please link me the post when it has been made (no rush), thank you,

**Pull request merged**
