### PR TITLE
Remove monero-meetup-kit-localization and monero-flyer

### PR DESCRIPTION
**Pull request by erciccione**
To be merged after monero-ecosystem/meta#34

### CODE REVIEW

**Comment by Lafudoci** [comment]
Is the  `Gemfile.lock` deleting intentional? I'm not expert in gem stuff, but the lock file could help local build in identical environments.

**Comment by erciccione** [comment]
Sorry, it wasn't. Fixed now.

**Comment by erciccione** [comment]
@Lafudoci This supposed to be merged after the repositories were removed in the meta repo.

**Comment by Lafudoci** [comment]
Oops, sorry, I didn't aware of that. Is it not determined yet?

**Comment by erciccione** [comment]
I wrote it in the description of this PR: https://github.com/monero-ecosystem/monero-ecosystem.github.io/pull/2#issue-275952066.

I just wanted to have it removed after it was actually removed from the Ecosystem first :).

**Pull request merged**
